# Generated by Django 3.2 on 2024-03-21 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_remove_customuser_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('username',)},
        ),
    ]
