# Generated by Django 3.2 on 2024-03-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
    ]
