# Generated by Django 3.2 on 2024-03-23 03:13

import django.contrib.auth.validators
from django.db import migrations, models
import yam_auth.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yam_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamuser',
            name='username',
            field=models.CharField(error_messages={'max_length': 'Имя пользователя не более 150 символов.', 'unique': 'Пользователь с таким именем существует'}, help_text='Не больше 150 символов. Буквы, цифры и @/./+/-/_ только.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), yam_auth.validators.NotMeValidator()], verbose_name='username'),
        ),
    ]
