# Generated by Django 3.2 on 2024-03-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yam_auth', '0002_alter_yamuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamuser',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
