# Generated by Django 3.2 on 2024-03-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yam_auth', '0003_yamuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('moderator', 'moderator')], default='user', max_length=150),
        ),
    ]
