# Generated by Django 3.2 on 2024-03-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yam_auth', '0003_yamuser_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamuser',
            name='password',
        ),
    ]
