# Generated by Django 3.2 on 2024-03-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yam_auth', '0004_alter_yamuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamuser',
            name='password',
        ),
        migrations.AlterField(
            model_name='yamuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('moderator', 'moderator')], default='user', max_length=100),
        ),
    ]
