# Generated by Django 3.2 on 2024-03-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yam_auth', '0006_yamuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamuser',
            name='password',
        ),
    ]
